import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState, type ReactNode } from "react";
import { Clock3, MapPin, Phone, Search, ShoppingBag, Star, X, Plus, Minus, ArrowRight } from "lucide-react";
import { products, type Product } from "../data/products";
import { restaurantConfig } from "../data/restaurant";

export const Route = createFileRoute("/")({ component: Index });
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const burgundy="#700b2c", cream="#fff9f0", peach="#fdf0e2", ink="#351f20";
type CartItem=Product & {qty:number; finalPrice:number; size?:string; crust?:string; extras?:string[]};

function Index(){
 const [cat,setCat]=useState("Destaques"),[q,setQ]=useState(""),[selected,setSelected]=useState<Product|null>(null),[cart,setCart]=useState<CartItem[]>([]),[showCart,setShowCart]=useState(false);
 const [opts,setOpts]=useState({size:"Grande",crust:"Tradicional",extras:[] as string[]});
 const cats=["Destaques","Pizzas","Combos","Bebidas","Sobremesas","Outros"];
 const list=useMemo(()=>products.filter(p=>p.available&&(cat==="Destaques"?p.featured:p.category===cat)&&`${p.name} ${p.description}`.toLowerCase().includes(q.toLowerCase())),[cat,q]);
 const featured=products.filter(p=>p.featured).slice(0,4), total=cart.reduce((s,p)=>s+p.finalPrice*p.qty,0),count=cart.reduce((s,p)=>s+p.qty,0);
 const open=(p:Product)=>{setSelected(p);setOpts({size:p.sizes?.[1]?.name||"Grande",crust:"Tradicional",extras:[]})};
 const add=()=>{if(!selected)return;const base=selected.sizes?.find(s=>s.name===opts.size)?.price??selected.price;const crust=selected.crusts?.find(c=>c.name===opts.crust)?.price??0;const extras=opts.extras.reduce((s,e)=>s+(selected.extras?.find(x=>x.name===e)?.price||0),0);setCart(c=>[...c,{...selected,qty:1,finalPrice:base+crust+extras,size:selected.sizes?opts.size:undefined,crust:opts.crust,extras:opts.extras}]);setSelected(null);setShowCart(true)};
 const change=(i:number,d:number)=>setCart(c=>c.map((x,n)=>n===i?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 const whatsapp=()=>{const text=cart.map(x=>`${x.qty}x ${x.name} — ${money(x.finalPrice*x.qty)}`).join("%0A");window.open(`https://wa.me/${restaurantConfig.whatsapp}?text=${encodeURIComponent("🍕 NOVO PEDIDO\n\n"+text+"\n\nTOTAL: "+money(total))}`,"_blank")};
 return <main style={{background:cream,color:ink}} className="min-h-screen overflow-x-hidden">
  <header className="sticky top-0 z-40 border-b border-[#eadfd4] bg-[#fffaf3]/95 backdrop-blur"><div className="mx-auto flex h-[62px] max-w-[1180px] items-center justify-between px-5"><a href="#inicio" className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#760b2d] text-[17px] text-white">●</span><span><b className="block font-serif text-[15px] leading-4 text-[#5e0927]">Torre de Pizza</b><small className="block text-[8px] tracking-wide text-[#9a817c]">Pizzaria artesanal • Campo Grande - RJ</small></span></a><nav className="hidden items-center gap-7 text-[11px] text-[#5f5050] md:flex"><a href="#cardapio">Cardápio</a><a href="#historia">Sobre</a><a href="#onde">Contato</a><span>◎</span></nav><a href={`https://wa.me/${restaurantConfig.whatsapp}`} target="_blank" rel="noreferrer" className="rounded-full bg-[#7a0d30] px-4 py-2 text-[10px] font-bold text-white">Pedir agora</a></div></header>
  <section id="inicio" className="relative min-h-[430px] overflow-hidden"><img src="https://pizza-prime-digital.lovable.app/assets/hero-pizza-52s91XwR.jpg" className="absolute inset-0 h-full w-full object-cover" alt="Pizza"/><div className="absolute inset-0 bg-gradient-to-r from-[#300611]/90 via-[#450818]/60 to-[#450818]/10"/><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-[#fff9f0] to-transparent"/><div className="relative mx-auto flex min-h-[430px] max-w-[1180px] items-center px-5 pb-5"><div className="max-w-[550px] text-white"><h1 className="font-serif text-[42px] font-bold leading-[.94] sm:text-[58px]">Sabor de verdade<br/><span className="text-[#f1cc75]">em cada fatia.</span></h1><p className="mt-4 max-w-[490px] text-[13px] leading-5 text-white/85">Massa artesanal, ingredientes frescos e o cheiro de forno a lenha que transforma qualquer noite em Campo Grande.</p><div className="mt-3 flex flex-wrap gap-3 text-[9px] text-white/90"><span>★ 4,2 (265 avaliações)</span><span>● Campo Grande, Rio de Janeiro – RJ</span><span>◷ Todos os dias, das 18h às 00h</span></div><div className="mt-3 flex gap-2 text-[9px]"><span className="rounded-full bg-white/15 px-3 py-1.5">Entrega</span><span className="rounded-full bg-white/15 px-3 py-1.5">Retirada</span><span className="rounded-full bg-white/15 px-3 py-1.5">Atendimento no local</span></div><div className="mt-4 flex gap-2"><a href="#cardapio" className="rounded-full bg-[#f4d47f] px-5 py-2.5 text-[10px] font-bold text-[#5d1b20]">Ver cardápio</a><a href={`https://wa.me/${restaurantConfig.whatsapp}`} target="_blank" rel="noreferrer" className="rounded-full border border-white/40 px-5 py-2.5 text-[10px] font-bold">Pedir no WhatsApp</a></div></div></div></section>
  <section className="bg-[#700b2c] px-5 py-10 text-white"><div className="mx-auto max-w-[1000px]"><div className="mb-5 flex items-end justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.25em] text-[#f2d17b]">Seleção da casa</p><h2 className="mt-1 font-serif text-[25px] font-bold">Os mais pedidos da torre</h2></div><button className="rounded-full border border-white/20 px-4 py-1.5 text-[9px]">Ver tudo</button></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{featured.map(p=><ProductCard key={p.id} p={p} compact onAdd={()=>open(p)}/>)}</div></div></section>
  <section id="cardapio" className="px-5 py-12"><div className="mx-auto max-w-[1000px]"><div className="text-center"><p className="text-[8px] font-bold uppercase tracking-[.3em] text-[#8d2445]">Nosso cardápio</p><h2 className="mt-1 font-serif text-[27px] font-bold">Escolha a sua fatia favorita</h2><p className="mx-auto mt-1 max-w-[480px] text-[9px] text-[#927e7b]">Tudo feito na hora, com massa de fermentação natural e queijo derretendo de verdade.</p></div><div className="mx-auto mt-6 max-w-[380px] rounded-full border border-[#eaded4] bg-white px-4 py-2 shadow-sm"><Search size={13} className="mr-2 inline text-[#9b8b87]"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-[90%] bg-transparent text-[9px] outline-none" placeholder="Buscar pizzas, bebidas, combos..."/></div><div className="mt-3 flex justify-center gap-1.5 overflow-x-auto">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`rounded-full px-3 py-1.5 text-[8px] ${cat===c?'bg-[#7a0d30] text-white':'border border-[#e7ddd5] bg-white text-[#725f5c]'}`}>{c}</button>)}</div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{list.map(p=><ProductCard key={p.id} p={p} onAdd={()=>open(p)}/>)}</div></div></section>
  <section id="historia" className="bg-[#fdf0e2] px-5 py-12"><div className="mx-auto grid max-w-[1000px] items-center gap-8 lg:grid-cols-[1fr_1fr]"><div className="relative"><img src="https://pizza-prime-digital.lovable.app/assets/about-pizzeria-C2ZPZmx1.jpg" className="aspect-[1.15] w-full rounded-[18px] object-cover" alt="Forno a lenha"/><div className="absolute -bottom-3 left-4 rounded-xl bg-white px-4 py-2 shadow-lg"><b className="font-serif text-xl text-[#760b2d]">+265</b><span className="ml-2 text-[8px] text-[#88716d]">avaliações públicas</span></div></div><div><p className="text-[8px] font-bold uppercase tracking-[.28em] text-[#9a2749]">Sobre a Torre de Pizza</p><h2 className="mt-2 font-serif text-[29px] font-bold leading-tight">Tradição de bairro, sabor de forno a lenha</h2><p className="mt-3 text-[10px] leading-5 text-[#7f6d68]">A Torre de Pizza, localizada em Campo Grande, no Rio de Janeiro, oferece uma experiência saborosa e prática para quem deseja pedir em casa, retirar no local ou aproveitar o atendimento presencial.</p><div className="mt-5 space-y-3">{[["Ingredientes de verdade","Massa de fermentação lenta e queijos selecionados."],["Acolhimento","Atendimento de bairro, com o carinho de sempre."],["Praticidade","Delivery rápido, retirada no balcão ou mesa na casa."]].map(([a,b])=><div key={a} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-white text-[#8a2041] shadow-sm">•</span><div><b className="text-[10px]">{a}</b><p className="text-[8px] text-[#907c77]">{b}</p></div></div>)}</div><div className="mt-5 flex items-center gap-2"><Star size={15} fill="#a7284d" className="text-[#a7284d]"/><div><b className="text-[11px]">4,2 / 5</b><p className="text-[8px] text-[#907c77]">Aproximadamente 265 avaliações públicas</p></div></div></div></div></section>
  <section className="bg-[#fdf0e2] px-5 pb-10"><div className="mx-auto grid max-w-[1000px] grid-cols-2 gap-3 lg:grid-cols-4"><Info icon="★" title="AVALIAÇÃO" value="4,2 / 5" detail="Aproximadamente 265 avaliações públicas"/><Info icon="◷" title="HORÁRIO" value="18h às 00h" detail="Todos os dias, das 18h às 00h"/><Info icon="⌖" title="ENDEREÇO" value="Campo Grande – RJ" detail="R. Domingos Alves Ribeiro, 20 — Campo Grande, Rio de Janeiro – RJ"/><Info icon="◌" title="TELEFONE" value="(21) 3356-2455" detail="Entrega, retirada e local"/></div></section>
  <section id="onde" className="px-5 py-10" style={{background:cream}}><div className="mx-auto max-w-[1000px] rounded-[18px] bg-[#7b0d31] p-6 text-white sm:p-8"><div className="grid items-center gap-6 lg:grid-cols-[1fr_1fr]"><div><p className="text-[8px] font-bold uppercase tracking-[.25em] text-[#f0cc72]">Onde nos encontrar</p><h2 className="mt-1 font-serif text-[25px] font-bold leading-tight">Venha, retire-se ou receba em casa</h2><p className="mt-3 text-[9px] text-white/75">⌖ {restaurantConfig.address}</p><p className="mt-1 text-[9px] text-white/75">☎ {restaurantConfig.phone}</p></div><div className="grid gap-2"><a href={restaurantConfig.googleMapsUrl} target="_blank" rel="noreferrer" className="rounded-full bg-white/10 px-5 py-2.5 text-center text-[9px]">↗ Como chegar</a><a href={`tel:${restaurantConfig.phone}`} className="rounded-full bg-white/10 px-5 py-2.5 text-center text-[9px]">☎ Ligar agora</a><a href={`https://wa.me/${restaurantConfig.whatsapp}`} target="_blank" rel="noreferrer" className="rounded-full bg-[#f1d176] px-5 py-2.5 text-center text-[9px] font-bold text-[#5d1b20]">Pedir no WhatsApp</a></div></div></div></section>
  <footer className="border-t border-[#eadfd4] bg-[#fffaf3] px-5 py-5"><div className="mx-auto flex max-w-[1000px] items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#760b2d] text-[10px] text-white">●</span><div><b className="block text-[10px] text-[#5e0927]">Torre de Pizza</b><small className="text-[7px] text-[#9a817c]">Todos os dias, das 18h às 00h</small></div></div><span className="text-[7px] text-[#9a817c]">© 2026 Torre de Pizza</span></div></footer>
  {count>0&&<button onClick={()=>setShowCart(true)} className="fixed bottom-4 left-1/2 z-30 -translate-x-1/2 rounded-full bg-[#7a0d30] px-5 py-3 text-[10px] font-bold text-white shadow-xl"><ShoppingBag size={13} className="mr-1 inline"/> Ver pedido · {count} · {money(total)}</button>}
  {selected&&<Modal p={selected} opts={opts} setOpts={setOpts} close={()=>setSelected(null)} add={add}/>} {showCart&&<Cart cart={cart} total={total} change={change} close={()=>setShowCart(false)} send={whatsapp}/>} 
 </main>
}

function ProductCard({p,compact,onAdd}:{p:Product;compact?:boolean;onAdd:()=>void}){return <article className={`overflow-hidden rounded-[15px] border border-[#eadfd4] bg-white shadow-[0_7px_20px_rgba(90,35,35,.08)] ${compact?'':'hover:-translate-y-0.5 transition'}`}><div className="relative"><img src={p.image} className={`w-full object-cover ${compact?'aspect-[1.05]':'aspect-[1.08]'}`} alt={p.name}/>{p.badge&&<span className="absolute left-2 top-2 rounded-full bg-[#7a0d30] px-2 py-1 text-[7px] font-bold text-white">{p.badge}</span>}</div><div className="p-3"><h3 className="font-serif text-[12px] font-bold">{p.name}</h3>{!compact&&<p className="mt-1 line-clamp-2 min-h-[24px] text-[8px] leading-3.5 text-[#8b7772]">{p.description}</p>}<div className="mt-2 flex items-center justify-between"><div>{p.oldPrice&&<del className="mr-1 text-[7px] text-[#b8aaa5]">{money(p.oldPrice)}</del>}<b className="text-[10px] text-[#5f2029]">{money(p.price)}</b></div><button onClick={onAdd} className="rounded-full border border-[#ead4ca] px-2 py-1 text-[7px] font-bold text-[#7a0d30]">+ adicionar</button></div></div></article>}
function Info({icon,title,value,detail}:{icon:string;title:string;value:string;detail:string}){return <div className="rounded-[15px] bg-white p-4 shadow-[0_6px_18px_rgba(90,35,35,.08)]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#7b0d31] text-[9px] text-white">{icon}</span><p className="mt-2 text-[7px] font-bold uppercase tracking-wider text-[#987f79]">{title}</p><b className="mt-1 block text-[10px]">{value}</b><p className="mt-1 text-[7px] leading-3 text-[#9a8681]">{detail}</p></div>}
function Modal({p,opts,setOpts,close,add}:{p:Product;opts:{size:string;crust:string;extras:string[]};setOpts:React.Dispatch<React.SetStateAction<{size:string;crust:string;extras:string[]}>>;close:()=>void;add:()=>void}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 p-0 sm:items-center sm:p-5"><div className="max-h-[90vh] w-full max-w-md overflow-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-[8px] font-bold uppercase tracking-widest text-[#8b2042]">Personalize</p><h3 className="font-serif text-2xl font-bold">{p.name}</h3></div><button onClick={close}><X size={20}/></button></div>{p.sizes&&<div className="mt-5"><b className="text-xs">Tamanho</b><div className="mt-2 flex gap-2">{p.sizes.map(s=><button key={s.name} onClick={()=>setOpts(o=>({...o,size:s.name}))} className={`rounded-full px-3 py-2 text-[9px] ${opts.size===s.name?'bg-[#7a0d30] text-white':'bg-[#f5ece5]'}`}>{s.name} · {money(s.price)}</button>)}</div></div>}{p.crusts&&<div className="mt-5"><b className="text-xs">Borda</b><div className="mt-2 flex flex-wrap gap-2">{p.crusts.map(s=><button key={s.name} onClick={()=>setOpts(o=>({...o,crust:s.name}))} className={`rounded-full px-3 py-2 text-[9px] ${opts.crust===s.name?'bg-[#7a0d30] text-white':'bg-[#f5ece5]'}`}>{s.name} {s.price?`+${money(s.price)}`:''}</button>)}</div></div>}<button onClick={add} className="mt-7 w-full rounded-full bg-[#7a0d30] py-3 text-xs font-bold text-white">Adicionar ao pedido</button></div></div>}
function Cart({cart,total,change,close,send}:{cart:CartItem[];total:number;change:(i:number,d:number)=>void;close:()=>void;send:()=>void}){return <div className="fixed inset-0 z-50 flex justify-end bg-black/40"><aside className="h-full w-full max-w-md overflow-auto bg-white p-5"><div className="flex justify-between"><h2 className="font-serif text-2xl font-bold">Seu pedido</h2><button onClick={close}><X/></button></div>{cart.length===0?<p className="py-10 text-sm text-gray-500">Seu carrinho está vazio.</p>:<>{cart.map((p,i)=><div key={`${p.id}-${i}`} className="flex gap-3 border-b py-4"><img src={p.image} className="h-16 w-16 rounded-xl object-cover"/><div className="flex-1"><b className="text-sm">{p.name}</b><p className="text-xs text-gray-500">{money(p.finalPrice)}</p><div className="mt-2 flex items-center gap-2"><button onClick={()=>change(i,-1)}><Minus size={14}/></button><span className="text-xs">{p.qty}</span><button onClick={()=>change(i,1)}><Plus size={14}/></button></div></div></div>)}<div className="flex justify-between py-5 font-bold">Total <span>{money(total)}</span></div><button onClick={send} className="w-full rounded-full bg-[#7a0d30] py-3 text-xs font-bold text-white">Enviar pedido pelo WhatsApp</button></>}</aside></div>}
