import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Clock3, MapPin, Minus, Phone, Plus, Search, ShoppingBag, Star, X } from "lucide-react";
import { restaurantConfig } from "../data/restaurant";
import { products, type Product } from "../data/products";

export const Route = createFileRoute("/")({ component: Index });
type Item = Product & { qty:number; finalPrice:number; size?:string; crust?:string; extras?:string[]; notes?:string };
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

function Index(){
 const [cat,setCat]=useState("Destaques"),[q,setQ]=useState(""),[cart,setCart]=useState<Item[]>(()=>JSON.parse(localStorage.getItem("pizza-cart")||"[]")),[pick,setPick]=useState<Product|null>(null),[drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false);
 const [opts,setOpts]=useState({size:"Grande",crust:"Tradicional",extras:[] as string[],notes:""});
 const [form,setForm]=useState({name:"",phone:"",type:"Delivery",address:"",number:"",neighborhood:"",payment:"PIX",change:""});
 useEffect(()=>localStorage.setItem("pizza-cart",JSON.stringify(cart)),[cart]);
 const cats=["Destaques","Pizzas","Combos","Bebidas","Sobremesas","Outros"];
 const list=useMemo(()=>products.filter(p=>p.available&&(cat==="Destaques"?p.featured:p.category===cat)&&(`${p.name} ${p.description}`).toLowerCase().includes(q.toLowerCase())),[cat,q]);
 const total=cart.reduce((s,x)=>s+x.finalPrice*x.qty,0), count=cart.reduce((s,x)=>s+x.qty,0);
 function open(p:Product){setPick(p);setOpts({size:p.sizes?.[1]?.name||"Grande",crust:"Tradicional",extras:[],notes:""})}
 function add(){if(!pick)return;const base=pick.sizes?.find(x=>x.name===opts.size)?.price??pick.price,cr=pick.crusts?.find(x=>x.name===opts.crust)?.price??0,ex=opts.extras.reduce((s,n)=>s+(pick.extras?.find(x=>x.name===n)?.price||0),0);setCart(c=>[...c,{...pick,qty:1,finalPrice:base+cr+ex,size:pick.sizes?opts.size:undefined,crust:opts.crust,extras:opts.extras,notes:opts.notes}]);setPick(null);setDrawer(true)}
 function qty(i:number,d:number){setCart(c=>c.map((x,n)=>n===i?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0))}
 function whatsapp(){const lines=cart.map(x=>`${x.qty}x ${x.name}${x.size?` ${x.size}`:""}${x.crust&&x.crust!=="Tradicional"?` | Borda ${x.crust}`:""}${x.extras?.length?` | ${x.extras.join(", ")}`:""} — ${money(x.finalPrice*x.qty)}`).join("\n");const addr=form.type==="Delivery"?`\n📍 ${form.address}, ${form.number} — ${form.neighborhood}`:"";const msg=`🍕 NOVO PEDIDO\n\n👤 ${form.name}\n📱 ${form.phone}\n\n🛒 PEDIDO\n${lines}\n\n💰 TOTAL: ${money(total)}\n🚚 ${form.type}${addr}\n💳 ${form.payment}${form.change?` — Troco para ${form.change}`:""}`;window.open(`https://wa.me/${restaurantConfig.whatsapp}?text=${encodeURIComponent(msg)}`,"_blank")}
 return <div className="min-h-screen bg-[#120f0d] text-[#f8f3ec]">
  <header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#120f0d]/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><a href="#inicio" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e6a23a] text-2xl">{restaurantConfig.logo}</span><b className="font-serif text-xl">{restaurantConfig.name}</b></a><nav className="hidden gap-7 text-sm text-white/65 md:flex"><a href="#cardapio">Cardápio</a><a href="#historia">Nossa história</a><a href="#onde">Onde estamos</a></nav><a target="_blank" href={`https://wa.me/${restaurantConfig.whatsapp}`} className="rounded-full bg-[#e6a23a] px-5 py-2.5 text-sm font-bold text-black">Pedir no WhatsApp</a></div></header>
  <section id="inicio" className="relative flex min-h-[760px] items-end overflow-hidden pt-20"><img src="https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=2000&q=90" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#100c0a] via-[#100c0a]/75 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-[#120f0d] to-transparent"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-20"><div className="max-w-2xl"><div className="text-xs font-bold uppercase tracking-[.25em] text-[#e6a23a]">Forno a lenha • desde 2012</div><h1 className="mt-5 font-serif text-6xl font-bold leading-[.92] sm:text-8xl">Sabor de verdade<br/><span className="text-[#e6a23a]">em cada fatia.</span></h1><p className="mt-7 max-w-xl text-lg leading-7 text-white/65">{restaurantConfig.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#cardapio" className="rounded-full bg-[#e6a23a] px-6 py-3.5 font-bold text-black">Ver cardápio <ArrowRight className="ml-1 inline" size={17}/></a><a target="_blank" href={`https://wa.me/${restaurantConfig.whatsapp}`} className="rounded-full border border-white/20 px-6 py-3.5 font-bold">Pedir no WhatsApp</a></div><div className="mt-9 flex flex-wrap gap-6 border-t border-white/15 pt-5 text-sm text-white/60"><span><Star className="mr-1 inline text-[#e6a23a]" size={15} fill="currentColor"/>4,8 Avaliações</span><span><MapPin className="mr-1 inline text-[#e6a23a]" size={15}/>São Paulo</span><span><Clock3 className="mr-1 inline text-[#e6a23a]" size={15}/>18h–00h</span></div></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20"><label className="text-xs font-bold uppercase tracking-[.25em] text-[#e6a23a]">Seleção da casa</label><h2 className="mt-2 font-serif text-5xl font-bold">Os mais pedidos</h2><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.filter(p=>p.featured).map(p=><Card key={p.id} p={p} onAdd={()=>open(p)}/>)}</div></section>
  <section id="cardapio" className="border-y border-white/10 bg-[#171310] px-5 py-20"><div className="mx-auto max-w-7xl"><label className="text-xs font-bold uppercase tracking-[.25em] text-[#e6a23a]">Nosso cardápio</label><h2 className="mt-2 font-serif text-5xl font-bold">Escolha a sua fatia favorita</h2><p className="mt-3 text-white/50">Tudo feito na hora, com massa artesanal e ingredientes selecionados.</p><div className="mt-8 flex max-w-2xl items-center gap-3 rounded-2xl border border-white/10 bg-[#0f0c0a] px-4 py-3"><Search size={19} className="text-white/35"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar pizzas, bebidas, combos..." className="w-full bg-transparent outline-none placeholder:text-white/30"/></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-semibold ${cat===c?"bg-[#e6a23a] text-black":"border border-white/10 text-white/60"}`}>{c}</button>)}</div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{list.map(p=><Card key={p.id} p={p} onAdd={()=>open(p)}/>)}</div></div></section>
  <section id="historia" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2 lg:items-center"><img src="https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=90" className="aspect-[4/3] w-full rounded-[2rem] object-cover"/><div><label className="text-xs font-bold uppercase tracking-[.25em] text-[#e6a23a]">+{restaurantConfig.reviewsCount} avaliações públicas</label><h2 className="mt-3 font-serif text-5xl font-bold">Tradição de bairro,<br/><span className="text-[#e6a23a]">sabor de forno a lenha.</span></h2><p className="mt-6 leading-7 text-white/60">Uma pizzaria feita para parecer marca de verdade: massa de fermentação lenta, ingredientes selecionados e atendimento próximo.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><Feature t="Ingredientes de verdade" d="Massa artesanal e produtos selecionados."/><Feature t="Acolhimento" d="Atendimento próximo e cuidadoso."/><Feature t="Praticidade" d="Delivery, retirada ou salão."/></div></div></section>
  <section id="onde" className="border-t border-white/10 bg-[#171310] px-5 py-20"><div className="mx-auto max-w-7xl"><label className="text-xs font-bold uppercase tracking-[.25em] text-[#e6a23a]">Onde nos encontrar</label><h2 className="mt-2 font-serif text-5xl font-bold">Venha, retire ou receba em casa.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Feature t="Endereço" d={restaurantConfig.address} icon={<MapPin/>}/><Feature t="Telefone" d={restaurantConfig.phone} icon={<Phone/>}/><Feature t="Horário" d={restaurantConfig.openingHours} icon={<Clock3/>}/><Feature t="Avaliação" d={`${restaurantConfig.rating.toFixed(1).replace('.',',')} / 5`} icon={<Star/>}/></div><div className="mt-7 flex flex-wrap gap-3"><a target="_blank" href={restaurantConfig.googleMapsUrl} className="rounded-full border border-white/15 px-5 py-3 font-semibold">Como chegar</a><a href={`tel:${restaurantConfig.phone}`} className="rounded-full border border-white/15 px-5 py-3 font-semibold">Ligar agora</a></div></div></section>
  <footer className="border-t border-white/10 px-5 py-9 text-sm text-white/40"><div className="mx-auto flex max-w-7xl justify-between"><b className="text-white/70">{restaurantConfig.logo} {restaurantConfig.name}</b><span>{restaurantConfig.openingHours} • © 2026</span></div></footer>
  {count>0&&<button onClick={()=>setDrawer(true)} className="fixed bottom-5 left-1/2 z-30 flex -translate-x-1/2 items-center gap-3 rounded-full bg-[#e6a23a] px-5 py-3.5 font-bold text-black shadow-2xl"><ShoppingBag size={18}/> Ver pedido <span>{count} itens • {money(total)}</span></button>}
  {pick&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/75 p-0 sm:items-center sm:p-5"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-t-[2rem] bg-[#1a1512] p-6 sm:rounded-[2rem]"><div className="flex justify-between"><div><small className="text-[#e6a23a]">PERSONALIZE</small><h3 className="font-serif text-3xl font-bold">{pick.name}</h3></div><button onClick={()=>setPick(null)}><X/></button></div><img src={pick.image} className="mt-5 h-48 w-full rounded-2xl object-cover"/><p className="mt-4 text-sm text-white/50">{pick.description}</p>{pick.sizes&&<Group title="Tamanho">{pick.sizes.map(o=><Opt key={o.name} a={opts.size===o.name} click={()=>setOpts({...opts,size:o.name})} text={o.name} add={o.price-pick.price}/>)}</Group>}{pick.crusts&&<Group title="Borda">{pick.crusts.map(o=><Opt key={o.name} a={opts.crust===o.name} click={()=>setOpts({...opts,crust:o.name})} text={o.name} add={o.price}/>)}</Group>}{pick.extras&&<Group title="Adicionais">{pick.extras.map(o=><Opt key={o.name} a={opts.extras.includes(o.name)} click={()=>setOpts({...opts,extras:opts.extras.includes(o.name)?opts.extras.filter(x=>x!==o.name):[...opts.extras,o.name]})} text={o.name} add={o.price}/>)}</Group>}<textarea value={opts.notes} onChange={e=>setOpts({...opts,notes:e.target.value})} placeholder="Observações" className="mt-5 min-h-20 w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none"/><button onClick={add} className="mt-4 w-full rounded-full bg-[#e6a23a] py-4 font-bold text-black">Adicionar ao pedido</button></div></div>}
  {drawer&&<div className="fixed inset-0 z-50 flex justify-end bg-black/70"><aside className="h-full w-full max-w-lg overflow-y-auto bg-[#181310] p-6"><div className="flex justify-between"><h3 className="font-serif text-3xl font-bold">Seu pedido</h3><button onClick={()=>setDrawer(false)}><X/></button></div>{!checkout?<><div className="mt-7 space-y-3">{cart.map((x,i)=><div key={i} className="flex gap-3 rounded-2xl border border-white/10 p-3"><img src={x.image} className="h-20 w-20 rounded-xl object-cover"/><div className="flex-1"><b>{x.name}</b><div className="text-xs text-white/40">{x.size} {x.crust!=="Tradicional"?`• ${x.crust}`:""}</div><div className="mt-2 flex justify-between"><span className="text-[#e6a23a]">{money(x.finalPrice*x.qty)}</span><span className="flex items-center gap-2"><button onClick={()=>qty(i,-1)}><Minus size={15}/></button>{x.qty}<button onClick={()=>qty(i,1)}><Plus size={15}/></button></span></div></div></div>)}</div><div className="mt-7 border-t border-white/10 pt-5"><div className="flex justify-between text-lg"><span>Total</span><b>{money(total)}</b></div><button onClick={()=>setCheckout(true)} className="mt-5 w-full rounded-full bg-[#e6a23a] py-4 font-bold text-black">Continuar pedido</button></div></>:<div className="mt-7 space-y-3"><button onClick={()=>setCheckout(false)} className="text-sm text-white/40">← Voltar</button><h4 className="font-serif text-2xl font-bold">Finalizar pedido</h4>{(["name","phone","address","number","neighborhood"] as const).map(k=><input key={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={{name:"Nome",phone:"Telefone",address:"Rua",number:"Número",neighborhood:"Bairro"}[k]} className="w-full rounded-xl border border-white/10 bg-white/[.03] px-4 py-3"/>)}<div className="grid grid-cols-2 gap-2"><button onClick={()=>setForm({...form,type:"Delivery"})} className={`rounded-xl border py-3 ${form.type==="Delivery"?"border-[#e6a23a]":"border-white/10"}`}>Delivery</button><button onClick={()=>setForm({...form,type:"Retirada"})} className={`rounded-xl border py-3 ${form.type==="Retirada"?"border-[#e6a23a]":"border-white/10"}`}>Retirada</button></div><select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#1a1512] px-4 py-3"><option>PIX</option><option>Dinheiro</option><option>Cartão na entrega</option></select>{form.payment==="Dinheiro"&&<input value={form.change} onChange={e=>setForm({...form,change:e.target.value})} placeholder="Troco para quanto?" className="w-full rounded-xl border border-white/10 bg-white/[.03] px-4 py-3"/>}<button onClick={whatsapp} className="w-full rounded-full bg-[#25d366] py-4 font-bold text-black">Finalizar pedido no WhatsApp</button></div>}</aside></div>}
 </div>;
}
function Card({p,onAdd}:{p:Product;onAdd:()=>void}){return <article className="overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#211a16]"><div className="relative"><img src={p.image} alt={p.name} className="aspect-[1.1] w-full object-cover transition hover:scale-105"/>{p.badge&&<span className="absolute left-3 top-3 rounded-full bg-[#e6a23a] px-3 py-1 text-[10px] font-bold uppercase text-black">{p.badge}</span>}</div><div className="p-5"><h3 className="font-serif text-xl font-bold">{p.name}</h3><p className="mt-2 min-h-12 text-sm text-white/45">{p.description}</p><div className="mt-4 flex items-center justify-between"><div>{p.oldPrice&&<div className="text-xs text-white/30 line-through">{money(p.oldPrice)}</div>}<b className="text-lg text-[#e6a23a]">{money(p.price)}</b></div><button onClick={onAdd} className="grid h-10 w-10 place-items-center rounded-full bg-white text-black hover:bg-[#e6a23a]"><Plus size={19}/></button></div></div></article>}
function Feature({t,d,icon}:{t:string;d:string;icon?:React.ReactNode}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="mb-3 text-[#e6a23a]">{icon}</div><small className="font-bold uppercase tracking-wider text-white/40">{t}</small><p className="mt-1 text-sm leading-6 text-white/65">{d}</p></div>}
function Group({title,children}:{title:string;children:React.ReactNode}){return <div className="mt-6"><b>{title}</b><div className="mt-3 grid gap-2 sm:grid-cols-3">{children}</div></div>}
function Opt({a,click,text,add}:{a:boolean;click:()=>void;text:string;add:number}){return <button onClick={click} className={`flex justify-between rounded-xl border px-3 py-3 text-sm ${a?"border-[#e6a23a] bg-[#e6a23a]/10 text-[#e6a23a]":"border-white/10 text-white/60"}`}>{text}{add>0&&<span>+{money(add)}</span>}</button>}
